SolveEveryday/Exercise

- Study01 - Implementation/Day01/kjh.java
- Study01 - Implementation/README.md
* _nums의 길이를 n이라고 함_
* 중복없는 배열 인덱스 두 개의 가능한 모든 조합을 이중 for문의 i, j로 순회하며
* i = 0~(n-1)
* j = (i+1)~(n-1)
* i, j번째 배열 원소의 합이 target과 같다면 [i, j]를 반환
시간복잡도 **O(N²)**
공간복잡도 **O(1)**
> 김진홍 1일차 문제 풀이

- Study01 - Implementation/Day02/ysm.cpp
- Study01 - Implementation/README.md
1.  a에서 z까지의 문자들을 인덱스 0부터 25까지라고 생각하고, 문자를 입력받을 때마다 alphabet배열의 해당 인덱스의 숫자를 증가시킴으로써 입력받은 횟수를 센다.
2. 가장 많이 입력받은 횟수를 찾고
3. 가장 많이 입력받은 횟수에 해당되는 알파벳을 출력한다. 
시간복잡도 O(N)
공간복잡도 O(N)
> 유수민 2일차 문제풀이

- Study01 - Implementation/Day03/hsk.js
- Study01 - Implementation/README.md
1. x를 절대값으로 변환
2. 문자열로 변환한 x를 뒤집음
3. 다시 숫자로 만들고 범위를 벗어나면 0을 return
4. 범위를 벗어나지 않았을 경우 음수면 -, 양수면 그대로 출력
시간복잡도 O(N)
공간복잡도 O(1)
- 범위 지정 안해서 한 번 실패함
> 황수경 3일차 문제 풀이

- Study01 - Implementation/Day03/ysm.cpp
- Study01 - Implementation/README.md
처음에 주어진 숫자 x를 10으로 나눈 나머지가 첫번째로 오는 숫자로 하고 주어진 숫자 x를 10으로 나눈 값으로 만든다. 다음에 올 숫자를 위해 앞에 언급한 방법을 주어진 숫자 x가 0이 될때까지 반복한다. 
시간복잡도 O(N)
공간복잡도 O(1)
* reverse 함수 적용하려다가 숫자 계산으로 방향 전환
* 계산식 만들려다 시간 소모를 엄청함.
* int 범위 벗어난 것으로 Runtime Error 발생
> 유수민 3일차 문제풀이

- Study01 - Implementation/Day04/hsk.js
- Study01 - Implementation/README.md
1. 후보자 추천들을 반복문으로 순회
2. 후보를 추천했다면 +1을 함
3. 아니라면 사진틀의 개수와 추천한 후보들의 개수를 비교
4. 3번이 같다면 사진틀이 전부 채워진 관계로 정렬 후 삭제
5. 남아있는 후보자들 번호를 정렬해 출력
시간복잡도 O(N²logN)
공간복잡도 O(N)
- 마지막에 정렬 때문에 계속 틀렸다..ㅠㅠㅠㅠ
- 로직은 분명 맞는데 테스트케이스만 통과해서 슬펐습니다..
> 황수경 4일차 문제 풀이

- Study01 - Implementation/Day04/kjh.java
- Study01 - Implementation/README.md
1. 추천 요청을 순서대로 처리한다
* 추천한 사진이 이미 있다면 추천수를 올린다
* 없다면 새로 등록한다
* 만약 자리가 꽉 찼다면, 등록하기 전에 가장 추천수가 낮고 추천받은지 오래 된 것을 먼저 하나 삭제한다
2. 남아있는 사진의 번호들을 정렬해 출력한다
시간복잡도 **O(N²)**
공간복잡도 **O(N)**
> 김진홍 4일차 문제 풀이

- Study01 - Implementation/Day05/hsk.js
- Study01 - Implementation/README.md
1. stairs에 계단의 수 만큼 배열 선언
2. 인덱스가 0일경우엔 기본, 1과 2일 경우에는 가장 큰 경우일 때를 점수 합산
3. 인덱스 3부터 N-1까지는 
Math.max(현재 계단 + 두계단 전 점수, 현재 계단 + 이전계단 + 3계단 전 점수)로 계산 누적
4. 마지막 누적 값 출력
시간복잡도 O(N)
공간복잡도 O(N)
> 황수경 5일차 문제 풀이

- Study01 - Implementation/Day05/kjh.kt
- Study01 - Implementation/README.md
continualCount: 연속으로 인접한 계단에 오른 횟수
index: ~번째 계단
index번째 계단에 오르는 경우의 수 중 가장 많은 점수를 얻을 때의 점수를 반환하는 함수
getAvailableMax(index, continualCount)
이 함수는 호출될 때마다 다시 재귀적으로 아래를 호출하고 둘 중 더 큰 값과 내 점수를 더해서 반환함
1. getAvailableMax(index-1, continualCount+1)
2. getAvailableMax(index-2, 1)
continualCount가 3이상이라면 Int.MIN_VALUE를 반환, index가 0 미만이라면 0을 반환하게 하여 예외처리 하였고
함수의 반환값을 memoizaiton하여 중복되는 계산에 대한 시간 효율을 높였음
getAvailableMax(마지막 인덱스, 1)를 호출하면 문제의 답이 구해짐
시간복잡도 **O(N)**
공간복잡도 **O(N)**
몇시간 동안 좀 고생했는데 덕분에 다이나믹 프로그래밍 개념 좀 다시 잡을 수 있었네요 ^^..
> 김진홍 5일차 문제풀이

- Study01 - Implementation/Day06/ysm.cpp
- Study01 - Implementation/README.md
1. 주어진 단어 개수 만큼 반복
2. 입력받은 단어의 각 자리 글자가 각각 0 ~ 26까지 범위에 해당하게 한 후, 
3. boolean인 알파벳 배열의 해당 글자 위치가 false일 경우, true로 만들고
4. boolean인 알파벳 배열의 해당 글자 위치가 true일 경우, 연속된 글자인지 판단하고 연속된 것이 아니면 count에서 1을 뺀다
5. count 출력
시간복잡도 O(N)
공간복잡도 O(1)
> 유수민 6일차 문제

- Study01 - Implementation/Day07/ysm.cpp
- Study01 - Implementation/README.md
1. 사각형의 왼쪽 위를 0으로 하고 각 지점에 대해서 거리는
가로 w, 높이 h, 입력 o라고 했을 때
*  북쪽 o
*  남쪽  2 * w + h - o
*  서쪽  2 * (w + h) - o
*  동쪽 w + o
동근이의 위치도 위처럼 나타낼 수 있다.
사진에서는 가로 r, 높이 c, 입력 d라고 지정하였다
2. 이렇게 나타낸 위치와 각 상점의 거리를 계산하여 최소 거리를 찾는다.
3. 계산한 거리가 최대거리의 절반을 넘어간다면 최대 거리에서 계산한 거리를 뺀다.
시간복잡도 O(N)
공간복잡도 O(1)
* 수학은 힘들다...
> 유수민 7일차 문제풀이

- Study01 - Implementation/Day12/kjh.kt
- Study01 - Implementation/README.md
1. 설문에 따라 각 유형에 1~3점을 부여한다
2. 네 유형에 대해 점수가 더 많은 유형을 선택하여 반환한다
* 동점인 경우 사전순으로 앞서는 글자유형
_N=survey.size_
시간복잡도 O(N)
공간복잡도 O(1)
> 김진홍 12일차 문제 풀이

- Study01 - Implementation/Day12/ysm.cpp
- Study01 - Implementation/README.md
vector<string>과 string에 대해 잘 알고 있어야 했다.
vector<string>의 특성상 들어온 문자를 분리해서 저장함. 즉, vector<string> survey 로 { 'RT', 'TR'} 로 입력된다면 survey[0][0]에 R, survey[0][1]에 T, survey[1][0]에 T, survey[1][1]에 R이 저장된다. 이 특성을 이용해서 만약 4로 나누었을 때 몫이 0이면 앞문자 1이 나오면 뒷문자에 점수를 더해주도록 하였다. 점수가 높은 문자를 결과 string에 더해주도록 하였다.
시간복잡도 O(N)
공간복잡도 O(1)
> 유수민 12일차 문제풀이

- Study01 - Implementation/Day13/kjh.kt
- Study01 - Implementation/README.md
1. l1 l2의 끝까지 순회한다
1. carry, l1, l2 값을 더한다 (l1이나 l2가 null이라면 값은 0으로 친다)
2. result 링크드리스트에 (더한 값 % 10)을 덧붙인다
3. carry에 (더한 값 / 10)을 넣는다
2. carry가 1이라면 result 뒤에 ListNode(1)을 덧붙인다
3. result를 반환한다
_N = max(l1.length, l2.length)_
시간복잡도 O(N)
공간복잡도 O(N)
전가산기를 프로그래밍 언어로 구현하는 느낌이었네요 재밌었습니다
> 김진홍 13일차 문제 풀이

- Study02 - Sort/Day16/kjh.kt
- Study02 - Sort/README.md
-1000000~1000000 범위를 가진 Boolean 배열을 만들어 입력되는 수에 대해 true로 체크하여 후에 순회하며 출력했습니다
시간복잡도 O(N)
공간복잡도 O(1)
> 김진홍 16일차 문제 풀이

- Study02 - Sort/Day17/kjh.kt
- Study02 - Sort/README.md
1. '다중 조건' '정렬' 문제라고 규정함
2. 다중 조건 처리는 아래와 같이 하였고
when문은 if ~ else if ~ else 와 비슷
3. 정렬은 퀵소트 알고리즘으로 했음
시간복잡도 O(NlogN)
공간복잡도 O(N)
> 김진홍 17일차 문제 풀이

- Study02 - Sort/Day18/kjh.kt
- Study02 - Sort/README.md
1. 숫자들을 입력받으며 각각의 숫자를 몇번째로 입력받았는지를 같이 기억한다
2. 정렬한다 (병합정렬 알고리즘 사용하였음)
3. 원래 위치와 바뀐 위치를 비교하여 가장 왼쪽으로 많이 움직인 횟수를 구한다
4. 가장 왼쪽으로 많이 움직인 횟수 + 1을 출력한다
시간복잡도 O(NlogN)
공간복잡도 O(N)
> 김진홍 18일차 문제 풀이

- Study02 - Sort/Day18/ysm.cpp
- Study02 - Sort/README.md
1. 구조체를 이용하여 숫자를 입력받음에 동시에 인덱스를 기록한다. 
2. 병합 정렬을 이용하여 정렬한다. 
3. 인덱스의 차를 구해서 그 값이 양수면 좌측으로 이동했다고 판단하고 인덱스의 차 중 가장 큰 값+1을 출력한다. 
시간복잡도 O(NlogN)
공간복잡도 O(1)
> 유수민 18일차 문제풀이

- Study02 - Sort/Day21/kjh.kt
- Study02 - Sort/README.md
1. 집합 A와 집합 B에 각각의 원소를 담는다
2. 차집합을 구하여 정렬한다
3. 정렬한 집합에 대한 크기와 원소들을 출력한다
시간복잡도 O(NlogN)
공간복잡도 O(N)
> 김진홍 21일차 문제풀이

- Study02 - Sort/Day21/ysm.cpp
- Study02 - Sort/README.md
* set이용
1) 집합 A와 B의 원소를 입력받는다. 
2)  B의 원소를 입력받을때 해당 원소가 A에 있는지 판단하고 없으면 다음 원소를 입력받고 있으면 해당 원소를 A에서 지워준다. 
3) 차집합에 해당하는 원소들의 개수와 해당 원소들을 출력한다. 
시간복잡도 O(NlogN)
공간복잡도 O(N)
> 유수민 21일차 문제풀이

- Study02 - Sort/Day22/ysm.cpp
- Study02 - Sort/README.md
* 우선순위 큐 사용 - 오름차순인 우선순위 (greater <> 사용)
1. 끝나는 시간 -> 시작시간 순으로 push 해준다. 
2. 현재시간보다 회의 시작시간이 작으면 넘어간다. 아니면 종료시간을 현재시간으로 설정하고 cnt를 증가한다. 
시간복잡도  O(NlogN)
공간복잡도  O(N)
> 유수민 22일차 문제풀이

- Study02 - Sort/Day24/ysm.cpp
- Study02 - Sort/README.md
1. 입력된 숫자를 인덱스로 생각하고 해당 배열의 수를 증가시킨다
2. 제시된 숫자의 인덱스 배열이 0이 아닐 경우 상근이가 가진 카드임을 인식하고 1로 출력한다. 0일경우는 0을 출력한다. 
N: card개수 M : 제시한 숫자 개수
시간복잡도 O(N+M)
공간복잡도 O(1)
> 유수민 24일차 문제풀이

- Study02 - Sort/Day26/kjh.kt
- Study02 - Sort/README.md
1. 마을의 위치를 기준으로 정렬한다
2. 자신을 기준으로 좌에 있는 마을들과 우에 있는 마을들의 인구수가 같거나 조금 넘어버리는 최초의 마을을 찾는다
3. 해당 마을의 위치를 출력한다
시간복잡도 O(NlogN+N)
공간복잡도 O(N)
1. sumOfPeople은 Long형으로 잘 지정해놓고 sum은 Int형으로 지정해버려서 오답이 나왔다.
> 김진홍 26일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day31/kjh.kt
- Study03 - Stack, Queue, Deque/README.md
1. 각 괄호들에 대해 VPS가 맞는지 확인한다
1. 각 괄호를 순회하며 아래를 수행한다
2. '('라면 push()
3. ')'라면
* 비어있다면 VPS가 아닌 것
* 비어있지 않다면 pop()
2. 스택에 괄호가 남아있다면 VPS가 아니고, 비어있다면 VPS다
5. 1에 대한 YES/NO 결과를 출력한다
_N=괄호들의 총 길이_
시간복잡도 O(N)
공간복잡도 O(N)
> 김진홍 31일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day31/ysm.cpp
- Study03 - Stack, Queue, Deque/README.md
1.입력 데이터수와 문자열 입력받기.
2. 만약 ( 가 나오면 stack에 넣기
3. )가 나올 경우
-- stack에 (가 있다면 stack에서 없앤다. 
-- 만약 stack이 비어있으면 조건에 부합하지 않으므로 No 출력한다. 
-- 해당 문자열을 다 확인했는데 stack이 비어있지 않으면 조건에 부합하지 않은 상태므로 No, stack이 비어있으면 Yes를 출력한다. 
시간복잡도 O(N)
공간복잡도 O(N)
> 유수민 31일차 문제풀이

- Study03 - Stack, Queue, Deque/Day34/kjh.java
- Study03 - Stack, Queue, Deque/README.md
1. 각 큐의 합을 구한다
2. 큐1 큐2 큐1 큐2를 합친 리스트를 하나 만든다 (단, 큐1의 합 > 큐2의 합)
* 4 6 5 1이 큐1, 3 2 7 2가 큐2라면
* 4 6 5 1 3 2 7 2 4 6 5 1 3 2 7 2 = 합친 리스트
* ^ ........ ^
* i .......... j
3. i와 j가 만나거나 인덱스가 배열을 벗어날때까지 아래를 반복한다
1. 목표 값보다 작아질 때까지 i 인덱스에 있는 것을 빼고 i++
2. 목표 값보다 커질 때까지 j 인덱스에 있는 것을 더하고 j++
3. 목표 값에 도달하면 현재까지 빼거나 더한 수를 반환
4. 3을 하는 내내 목표 값에 도달하지 못했다면 -1을 반환
시간복잡도 O(N)
공간복잡도 O(N)
벽이 느껴지네요
> 김진홍 34일차 문제 풀이 실패

- Study03 - Stack, Queue, Deque/Day35/kjh.kt
- Study03 - Stack, Queue, Deque/README.md
1. 덱에 1~N을 채워넣는다
2. 덱이 빌때까지(N번) 아래를 반복한다
1. N-1번 pop/push 하고
2. pop한 것을 출력
* 매 K번째마다 방향을 바꾼다
* 덱을 실제로 뒤집지는 않고
* push와 pop이 거꾸로 되게끔 구현했다
시간복잡도 O(NK)
공간복잡도 O(N)
> 김진홍 35일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day36/hhs.java
- Study03 - Stack, Queue, Deque/README.md
분배법칙을 이용한다
```
2 * (2 + 3 * (4 + 5)) = 2 * (2 + 12 + 15) = 4 + 24 + 30 = 58
```
곱하는 값을 미리 지정하기위해 temp 변수를 1로 선언하고 최종적으로 값을 출력할 answer를 0으로 지정한다.
문자열을 하나씩 순회하면서 각 조건에 맞게 스택에 빼거나 넣는다.
1. 스택이 비어있으면 값을 넣고 temp에 값(해당 문자가 '('면 2, '['면 3)을 곱한다.
2. stack의 peek가 열린괄호, 현재 문자가 닫힌 괄호 그리고 짝이 맞으면 스택의 값 pop한다.
2-1. 그 전단계 문자가 닫힌 괄호가 아니라면 answer에 temp를 더한다.
2-2. 현재 문자에 따라서 temp를 해당 값( ')'면 2, ']'면 3)으로 나눈다.
3. 그 외의 경우에는 열린 괄호가 겹치는 경우다 현재 문자에 따라 temp에 값('('면 2, '['면 3)을 곱하자.
시간복잡도 - O(N)
공간복잡도 - O(N)
오랜만에 희열감이 느껴지는 문제 였던 것 같습니다.
> 한현수 36일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day36/kjh.kt
- Study03 - Stack, Queue, Deque/README.md
1. 재귀함수 f()가 괄호를 순회하며 아래를 수행한다
* idx가 괄호의 길이를 벗어날때까지 아래를 반복한다
* 여는 괄호일 경우 `stacked += 2|3 * f()`
* 닫는 괄호일 경우 stacked가 0이라면 1을 반환, 아니라면 stacked 값을 그대로 반환 (위 공식에서 3\*1=3, 2\*1=2가 되게 하기위함)
* idx++
* 아래의 경우 error가 발생했다고 판정한다
* 닫는 괄호인데 stack이 비어있는 경우
* 닫는 괄호인데 stack.top()의 아이템과 짝이 맞지 않는 경우 (]
* 괄호의 길이를 벗어났는데 stack.size가 0이 아닌 경우
2. error가 발생했다면 0을, 발생하지 않았다면 1의 반환값을 출력한다
_N=괄호의 길이_
시간복잡도 O(N)
공간복잡도 O(N)
> 김진홍 36일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day39/jhd.cpp
- Study03 - Stack, Queue, Deque/README.md
자료구조 : deque
가장 앞 원소가 배포 가능한 100이상의 상태가 되어야 미리 완료된 뒤 원소들도 배포가 가능합니다.
1. 현재 상태에 증가율을 계속 더합니다.
2. 가장 앞 프로세스 원소가 100%가 되면 조건에 걸립니다.
2-1. 연속되는 100%가 넘는 원소가 있는지 확인하고 cnt를 셉니다.(중간에 100이 되지 않는 원소가 있으면 그 전까지만 카운트합니다.
2-2. cnt만큼 프로세스와 증가율을 제거하고 answer에 한번에 제거된 프로세스들이 몇개인지 저장합니다.(cnt 저장)
3. 프로세스가 비면 반복을 중단합니다.
시간복잡도 O(N)
공간복잡도 O(N)
오랜만에 문제해석부터 설계, 수도코드 작성까지 1시간이 걸리지 않는 문제였습니다. 이렇게 푸니 너무 재밌네요.
한문제를 풀때 집중할 수 있는 시간을 최대한 끌어 올려봐야겠어요.
> 정희두 39일차 문제풀이

- Study03 - Stack, Queue, Deque/Day38/jhd.cpp
- Study03 - Stack, Queue, Deque/README.md
<오답풀이>
자료구조는 변경하고 풀이 방식을 제 방식대로 바꿔서 다시 한번 구현해봤습니다.
자료구조 : Deque
몇대의 트럭이던 다리 위에서 계속 움직입니다. 
무게 제한으로 인해 트럭이 들어오지 못하는 경우 트럭의 발자취를 0으로 표시합니다.
대기줄이 없으면 마지막 트럭이 다리에 진입한 것으로 판단합니다.
<While문 종료 조건>
마지막으로 진입한 트럭은 다리 길이만큼만 움직이면 됩니다. 다리길이를 결과에 더해주고 While문을 종료합니다.
break 조건이 아닌 모든 행위는 1초로 카운팅 됩니다.
현재 다리에 0과 트럭으로 가득 찼다면 다리의 맨 앞 원소를 빼주고 다리 위 트럭 무게도 빼줍니다.
무게 제한에 따라 로직이 달라집니다.
1. 다리 위 트럭들이 무게제한에 걸리지 않았을 때
대기 줄에서 트럭을 다리 위로 보냅니다.
2. 무게 제한에 걸렸을 떄
0을 통해 이동 시킵니다. 
<회고>
무조건 다리길이 + 다리 위 트럭수 라고 생각한 거에서 생각을 리셋하지 못하고 이 생각만 했습니다. 
2시간 초과로 오답풀이 했습니다.
앞으로는 조금 더 단순하게 사고하고 가설을 세우고 검증이 안되면 다른 방식을 생각해보는 방향으로 해야겠습니다.
시간복잡도 O(N)
공간복잡도 O(N)
아무리 많아봤자 다리 길이 정도가 필요합니다.
시간 초과입니다.
> 정희두 38일차 오답풀이

- Study03 - Stack, Queue, Deque/Day38/ysm.cpp
- Study03 - Stack, Queue, Deque/README.md
1. vector에 있는 트럭 무게가 weight이하인지 검사해서 만약 이하면 다리에 오른 트럭 큐에 넣는다. 
2. 무게도 트럭무게만큼 더해준다.
3.  다음 인덱스 검사를 위해 인덱스를 증가시킨다. 
4. 1~3과정을 반복하고 answer도 증가시킨다. 
5. 무게검사를 하다가 weight이하가 아니면 다리에 오른 트럭 큐에 vector길이가 될때까지 계속 0을 넣는다. 
6. vector길이가 되면 첫번째 원소를 없앤다
7. 위의 과정을 idx가 vector 마지막 인덱스가 될때까지 반복한다.  
N : answer수 M : vector크기
시간복잡도 O(N)
공간복잡도 O(M)
> 유수민 38일차 문제풀이

- Study03 - Stack, Queue, Deque/Day39/ysm.cpp
- Study03 - Stack, Queue, Deque/README.md
1. 작업일수를 계산한다. 
(100 - 작업된상황)/속도 식에서 몫이 작업일수이다. 만약 나머지가 있을 경우 하루가 추가되니 하루를 더 더한다.
2. 앞쪽부터 최대작업일수를 구해서 다음 최대작업일수가 나올때까지 answer 큐값을 증가시킨다. 
3. 다음 최대작업일수가 나올 경우 answer의 idx를 옮긴다. 
N : progresses의 크기
시간복잡도 O(N)
공간복잡도 O(N)
> 유수민 39일차 문제풀이

- Study03 - Stack, Queue, Deque/Day38/hhs.java
- Study03 - Stack, Queue, Deque/README.md
다리를 건너는 트럭의 큐(A), 대기 트럭의 큐(B) 두개를 사용하자.
1. truck_weights에 지정된 트럭들을 대기 트럭에 순서대로 넣는다.
2. 반복문을 시작한다. A나 B가 둘중 하나 비어있으면 반복을 멈춘다.
2-1. A가 비어있으면 B의 값을 poll해서 A에 add한다. 그리고 해당 값의 중량을 따로 지정한 totalWeight(현재 다리의 중량 초기값:0) 변수에 더한다. 반복을 건너뛴다.
2-2. A에서 모든 트럭의 시간을 1씩 더한다.
2-3. A에서 맨 앞 트럭의 시간이 bridge_length의 값 이상이면 건널 준비가 됬다는 의미. poll하는 동시에 해당 값을 totalWeight 변수에 뺀다.
2-4. B가 비어있지않고 맨 앞 트럭의 중량이 totalWeight과 더한 값이 weight(다리 최대 중량)의 값 이하라면 해당 값을 B에서 뺴고 A에 넣는다.
3. 반복한 시간을 출력한다.
여기서 N은 truck_weights의 길이를 의미한다.
시간복잡도 - O(N)
공간복잡도 - O(N)
> 현수 38일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day39/hhs.java
- Study03 - Stack, Queue, Deque/README.md
몇일차에 배포를 몇개했는지 알기위해 100의 길이를 가지는 days 1차원 배열 생성
1. progresses, speeds를 각 인덱스 별로 순회한다.
2. 큐에 Math.ceil((100 - progress) / (double) speed)의 값을 집어넣는다. <- 이때 해당값은 몇일차인지를 의미한다. 따라서 2번의 작업을 모두 마치면 몇일차에 배포되는지의 일차들이 모여있다.
3. 큐에서 poll을 하여 max 변수에 넣고 days[max]의 값을 1 더한다.
4. 큐가 비워질때 까지 반복하는데 한개씩 poll하여 max와 비교하여 해당 값이 max보다 크다면 max에 대입하고 days[max]의 값을 1 더한다.
5. days에 순차적으로 0이 아닌 값을 출력한다.
N은 progresses, speeds배열의 길이
시간복잡도 - O(N)
공간복잡도 - O(N)
> 한현수 39일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day40/kjh.kt
- Study03 - Stack, Queue, Deque/README.md
자료구조: Stack
1. 타워를 역순으로 순회하며 아래를 수행한다 (입력이 1 2 3이라면 3 2 1순으로)
* peek보다 큰 값이 올때까지는
* 그냥 push만 한다
* peek보다 크거나 같은 값이 들어온다면
* 현재 높이보다 작거나 같은 값들을 전부 pop하며
* pop된 타워의 '수신 타워 번호'를 현재의 번호로 설정한다
* 현재 타워를 push
2. 수신 타워 번호들을 출력한다
시간복잡도 O(N)
공간복잡도 O(N)
> 김진홍 40일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day40/jhd.cpp
- Study03 - Stack, Queue, Deque/README.md
1. 스택에는 탑의 높이와 인덱스를 저장한다.
2. 맨 우측 탑부터, 스택이 비었다면 스택에 현재 탑의 높이와 인덱스를 저장하고,
3. 스택이 비지 않았다면, 스택이 비지 않고, 스택 top의 탑의 높이가 현재 탑의 높이보다 작은 동안
4. 스택 top의 탑의 인덱스에 현재 인덱스를 저장합니다.
시간복잡도 O(N)
공간복잡도 O(N)
> 정희두 40일차 문제풀이

- Study03 - Stack, Queue, Deque/Day40/hhs.java
- Study03 - Stack, Queue, Deque/README.md
1. 입력받은 숫자를 순회한다.
2. 스택의 peek의 height가 현재 입력받은 height보다 작다면 pop하고 크거나 같다면 해당 인덱스를 저장한다.
3. 입력받은 숫자를 스택에 넣는다.
4. 1~3번 과정을 N번 반복한다.
시간복잡도 - O(N)
공간복잡도 - O(N)
> 한현수 40일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day40/ysm.cpp
- Study03 - Stack, Queue, Deque/README.md
1. 탑높이를 입력받은 후 스택이 비어있을 경우 0을 출력하고 해당 인덱스와 탑의 높이를 스택에 넣는다. 
2.  다시 탑높이를 입력받고 스택의 최상위의 것이 입격받은 값보다 작으면 스택에 있던 것을 pop하고 현재 값을 인덱스값과 함께 넣는다. 
3. 스택의 최상위의 것이 현재 입력받은 값보다 크면 스택의 인덱스값을 출력한다. 
N:스택의 크기
시간복잡도 O(N)
공간복잡도 O(N)
> 유수민 40일차 문제 풀이

- Study03 - Stack, Queue, Deque/Day41/kjh.kt
- Study03 - Stack, Queue, Deque/README.md
모두 입장 완료(=GOOD)하거나 BAD 판정이 나올때까지 아래를 반복한다
1. 줄의 제일 앞 사람이 바르게 입장하는 순서라면 콘서트장에 들여보낸다
2. 대기 공간의 제일 앞 사람이 바르게 입장하는 순서라면 콘서트장에 들여보낸다
3. 줄이 비었는데 대기 공간의 제일 앞 사람이 바른 순서가 아니라면 BAD 판정
4. 대기 공간에도 줄에도 바르게 입장하는 순서의 사람이 없다면
* 줄의 제일 앞 사람을 대기 공간의 제일 앞으로 보낸다
_N=티켓 수_
시간복잡도 O(N)
공간복잡도 O(N)
> 김진홍 41일차 문제풀이

- Study04 - Priority Queue/Day45/ysm.cpp
- Study04 - Priority Queue/README.md
1. 입력받는다. 
2. 자연수면 우선순위 큐에 넣는다. 
3. 0이면
-- 만약 큐가 비어있으면 0 출력
-- 큐가 들어있으면 가장 큰수 출력후 pop
시간복잡도 O(NlogN)
공간복잡도 O(N)
행복은 술술 풀리는 문제에서 온다~~~
> 유수민 45일차 문제풀이

- Study05 - Recursion/Day51/jhd.cpp
- Study05 - Recursion/README.md
Call Stack
재귀함수에 별다른 연산이 없다면 시간복잡도와 공간복잡도는 같아진다.
1. 재귀의 종료조건으로 제곱수가 1일때 a%c를 반환합니다.
2. a%c를 두번 곱하고 모듈러 연산을 한 결과를 반환합니다.
3. 만약 홀수라면 짝수결과값에 원본값을 곱하고 다시 나머지 연산을 합니다.(홀수일 경우 마지막 연산에 적용됩니다. / 에서 짝수로 진행됩니다.)  
Long 타입은 최대인 20억에 2만 곱하더라고 Int의 범위를 초과합니다. 당연히 long을 사용해야합니다.
[N이 짝수]
2^N= 2^N/2 * 2^N/2
2^N/2 = 2^N/4 * 2^N/4
[N이 홀수]
2^N = 2^1 * 2^N/2 * 2^N/2	
2^N/2 = 2^N/4 * 2^N/4
홀수일 경우 마지막에만 기준값을 곱해주는 방식으로 진행됩니다. 위에서 본것과 같이 홀수일 경우에는 2를 한번 더 곱해주면 됩니다. 계산상으로 처음에 곱해야하지만 재귀는 결국 마지막 연산에 곱해진다고 생각하면됩니다.
시간복잡도 O(logN)
결국 재귀함수를 통해 절반씩 나누면서 정복하게되기 때문에 logN의 시간 복잡도를 가지고 갈 수 있습니다.
공간복잡도 O(logN)
Call Stack을 이용하기 때문에 시간복잡도와 같습니다.
> 정희두 51일차 문제풀이

- Study05 - Recursion/Day55/kjh.kt
- Study05 - Recursion/README.md
스택, 올바른 문자열인지 판단하기 위해서
문제에서 주어진 그대로 짰음
1. 입력이 빈 문자열인 경우, 빈 문자열을 반환합니다. 
2. 문자열 w를 두 "균형잡힌 괄호 문자열" u, v로 분리합니다. 단, u는 "균형잡힌 괄호 문자열"로 더 이상 분리할 수 없어야 하며, v는 빈 문자열이 될 수 있습니다. 
3. 문자열 u가 "올바른 괄호 문자열" 이라면 문자열 v에 대해 1단계부터 다시 수행합니다. 
3-1. 수행한 결과 문자열을 u에 이어 붙인 후 반환합니다. 
4. 문자열 u가 "올바른 괄호 문자열"이 아니라면 아래 과정을 수행합니다. 
4-1. 빈 문자열에 첫 번째 문자로 '('를 붙입니다. 
4-2. 문자열 v에 대해 1단계부터 재귀적으로 수행한 결과 문자열을 이어 붙입니다. 
4-3. ')'를 다시 붙입니다. 
4-4. u의 첫 번째와 마지막 문자를 제거하고, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙입니다. 
4-5. 생성된 문자열을 반환합니다.
시간복잡도 O(N) : 하나의 재귀호출마다 적어도 하나의 괄호(맨 앞과 맨 뒤)가 바로 잡아지기때문에
공간복잡도 O(N)
> 김진홍 55일차 문제 풀이

- Study05 - Recursion/Day55/ysm.cpp
- Study05 - Recursion/README.md
스택과 재귀를 사용하였습니다. 
제시된 로직 그대로 수행하였습니다. 
1. 입력이 빈 문자열인 경우, 빈 문자열을 반환한다
2. 문자열 w를 두 "균형잡힌 괄호 문자열" u, v로 분리한다. 단, u는 "균형잡힌 괄호 문자열"로 더 이상 분리할 수 없어야 하며, v는 빈 문자열이 될 수 있다. 
3. 문자열 u가 "올바른 괄호 문자열" 이라면 문자열 v에 대해 1단계부터 다시 수행한다. 
-- 수행한 결과 문자열을 u에 이어 붙인 후 반환. 
4. 문자열 u가 "올바른 괄호 문자열"이 아니라면 아래 과정을 수행한다. 
-- 빈 문자열에 첫 번째 문자로 '('를 붙인다. 
-- 문자열 v에 대해 1단계부터 재귀적으로 수행한 결과 문자열을 이어 붙인다. 
-- ')'를 다시 붙인다. 
-- u의 첫 번째와 마지막 문자를 제거하고, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙인다. 
-- 생성된 문자열을 반환한다.
시간복잡도 O(N)
공간복잡도 O(N)
> 유수민 55일차 문제풀이

- Study05 - Recursion/Day56/hhs.java
- Study05 - Recursion/README.md
재귀 - 재귀적으로 호출해야하기 때문
1. 모든 수들이 다 같은지 확인한다. 같다면 함수를 멈춘다.
2. 1번에서 같지않다면 면을 4등분으로 나눠 왼쪽위, 오른쪽위, 왼쪽아래, 오른쪽 아래 순으로 1번과정으로 다시 돌아간다.
4영역으로 나누어 확인하는 로직이 재귀함수를 쓰기에 적당한 문제라고 생각했습니다.
시간복잡도 - O(4^log_2(N)) - 재귀함수를 4번호출하고 또 log_2(N)만큼 반복한다.
공간복잡도 - O(N^2): 쿼드트리는 N*N입니당.
> 한현수 56일차 문제 풀이

- Study05 - Recursion/Day55/hhs.java
- Study05 - Recursion/README.md
스택 - 올바른 괄호인지 판단하기 위함.
재귀 - 재귀적으로 호출하는 문제임
1. 입력이 빈 문자열인 경우, 빈 문자열을 반환합니다. 
2. 문자열 w를 두 "균형잡힌 괄호 문자열" u, v로 분리합니다. 단, u는 "균형잡힌 괄호 문자열"로 더 이상 분리할 수 없어야 하며, v는 빈 문자열이 될 수 있습니다. 
3. 문자열 u가 "올바른 괄호 문자열" 이라면 문자열 v에 대해 1단계부터 다시 수행합니다. 
3-1. 수행한 결과 문자열을 u에 이어 붙인 후 반환합니다. 
4. 문자열 u가 "올바른 괄호 문자열"이 아니라면 아래 과정을 수행합니다. 
4-1. 빈 문자열에 첫 번째 문자로 '('를 붙입니다. 
4-2. 문자열 v에 대해 1단계부터 재귀적으로 수행한 결과 문자열을 이어 붙입니다. 
4-3. ')'를 다시 붙입니다. 
4-4. u의 첫 번째와 마지막 문자를 제거하고, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙입니다. 
4-5. 생성된 문자열을 반환합니다.
문제 그대로 구현을 했습니다.
시간복잡도 - O(N)
공간복잡도 - O(N)
N번만큼의 재귀 발생
> 한현수 55일차 문제 풀이

- Study05 - Recursion/Day57/ysm.cpp
- Study05 - Recursion/README.md
input된 문자열의 번호를 확인하려면 path라는 문자열에 일정 순서대로 문자들을 담아야한다. 
이런 로직은 재귀가 적합하였다. 
AEIOU라는 문자열을 통해 분기가 5개임을 알 수 있고, 최대 5개의 문자를 이용해 단어를 만들 수 있으니 5개의 level임을 알 수 있다. 각 층의 분기에 해당하는 name을 path에 넣어주고 만약 반환되면 마지막으로 넣어준 문자를 제외한 앞부분을 path에 다시 넣는 방식을 이용했다. 
입력받은 문자열과 비교하고 아니라면 cnt를 세서 번호를 입력하도록 하였다. 
트리를 만드는데 level 은 5고 branch가 5가 나옴을 확인했고 이를 그대로 코드로 구현하였다. 
시간복잡도 O(5^n)
공간복잡도 O(1)
분기가 5라서 5^n으로 시간복잡도를 썼는데 확신하지 못한다. 만들 수 있는 단어의 size가 5이기 때문에 path의 사이즈가 최대 5라고 생각해서 공간복잡도를 1로 잡았다. 
시간 복잡도, 공간복잡도 맞는지 확인 해주세요ㅠ
> 유수민 57일차 문제풀이

- Study06 - Exhaustive Search/Day60/kjh.kt
- Study06 - Exhaustive Search/README.md
ArrayList: 뽑을 카드 목록을 담기 위해서
HashSet: 카드의 조합을 문자열로 이은 것을 중복없이 저장하기 위해서
재귀함수 mixCards(cards, pickCount)를 작성했다.
(cards는 뽑을 수 있는 카드의 목록, pickCount는 뽑을 개수)
pickCount가 1이라면 cards를 그대로 반환하고
2 이상이라면
* 뽑을 수 있는 카드들에 대하여 순회하며 아래를 수행한다 (card)
* 재귀호출로 pickCount-1개의 조합을 반환받는다. (뽑을 수 있는 카드에서 자신은 제외하여 파라미터를 넘긴다)
* 조합에 대해 순회하며 아래를 수행한다 (cardsStr)
* card + cardsStr을 Set에 추가한다
모든 순회가 끝나면 Set을 반환하고
main에서는 Set의 크기를 출력한다
중첩 for문 10개를 쓸 수는 없으니 재귀를 사용
시간복잡도 O(N^K)
공간복잡도 O(N^K)
1개의 카드를 뽑는 경우의 수 N
2개의 카드를 뽑아 조합을 만드는 경우의 수 N*(N-1)
3개의 카드를 뽑아 조합을 만드는 경우의 수 N\*(N-1)*(N-2)
4개의 카드를 뽑아 조합을 만드는 경우의 수 N\*(N-1)\*(N-2)\*(N-3)
> 김진홍 60일차 문제풀이

- Study06 - Exhaustive Search/Day64/kjh.kt
- Study06 - Exhaustive Search/README.md
e, s, m을 1부터 시작해서
입력의 e, s, m이 될때까지 계속 +1하고 (경계값을 넘어가면 다시 1로)
목표 e, s, m이 되었을때 year을 출력한다
입력이 매우 작아서
완전탐색하라고 푼 문제구나 하고 풀었다
시간복잡도 O(E*S*M) : 목표 ESM만큼 반복이 수행됨
공간복잡도 O(1)
> 김진홍 64일차 문제 풀이

- Study07 - Divide And Conquer/Day65/kjh.kt
- Study07 - Divide And Conquer/README.md
리스트, 수들을 담기 위해
문제에서 원하는걸 간략하게 정리하면
결국
1. N/K개의 덩어리로 나눈 것을
2. 각각 정렬하고
3. 다시 합친 걸 출력하는 것이다.
시간복잡도 K*(N/K)log(N/K)
공간복잡도 O(N)
N/K 사이즈를 정렬하면 (N/K)log(N)이고
그 정렬을 K번 하므로 여기에 K를 곱함
> 김진홍 65일차 문제 풀이

- Study07 - Divide And Conquer/Day67/jhd.cpp
- Study07 - Divide And Conquer/README.md
그저 재귀, 분할 정복 
기본적으로 크기는 long입니다. int이면 두번만 곱해도 범위를 초과합니다. 
1. 곱하는 횟수가 1이되면 a를 c로 모듈러 연산한 값을 반환합니다.
2. 결과 값을 두번 곱하고 모듈러 연산을 진행합니다.
3. b가 홀수일 경우 정확히 절반으로 떨어지지 않고 1번의 곱셉이 남습니다. 
4. 따라서 결과에 기준값을 c로 모둘러 연산을 한 값을 곱해줍니다.
모둘러 연산 (a * a * a) %c == a%c *a%c *a%c 
2^4 == 2^2 * 2^2
큰 수는 둘로 쪼개고 한쪽만 연산을 통해 구하고 그 수를 두번 곱하면 해당 연산을 조금하고 답을 구할 수 있습니다. 이 방식을 이용해서 풀이하였습니다.
시간복잡도 O(logb)
절반씩 나눠서 해답을 구할 것이기 때문에 logB가 됩니다.
공간복잡도 O(logb)
stack이 필요 즉 연산에 필요한 함수의 갯수면 충분합니다.
> 정희두 67일차 문제풀이

- Study07 - Divide And Conquer/Day68/ysm.cpp
- Study07 - Divide And Conquer/Day68/ysm.java
- Study07 - Divide And Conquer/README.md
C++은 성공했으나,
자바의 경우, 다른 사람의 풀이를 참고 하였습니다. 
1) 입력이 끝나는 경우 판단 -> while((str = br.readLine() != null)
2) 제곱 : Math.pow(밑,지수)
3) 문자열 : StringBuilder v = new StringBuilder();
4) 문자열에 문자 붙이기 : v. append()
5) 해당 인덱스에 해당하는 곳에 문자 바꾸기: v.setCharAt(인덱스,바꿀문자)
재귀 - 3등분하고 2번째 공간을 빈문자열로 만드는 행위가 반복되므로
입력받은 숫자만큼 문자열에 -을 채워준후, 3으로 나누었을때 2번째 공간에 해당하는 인덱스 칸을 다시 빈문자열로 채운다. 나머지 첫번째, 세번째 공간을 방금 행한 과정을 반복한다. 
문제에서 말한 그대로 짰다. 
시간복잡도 O(2^log_3(N)) 
-> 재귀를 2번씩 부르고 27 -> 9 -> 3 ->1이므로 2^log_3(N)이다. 
공간복잡도 O(3^N)
> 68일차 유수민 문제 풀이

- Study08 - Dynamic Programming/Day73/hhs.java
- Study08 - Dynamic Programming/README.md
배열 - 값들을 저장하기 위해서
이 문제는 최장 증가 부분 수열(LIS)에 관한 문제이다.
값을 저장할 배열 values와 연속적인 길이를 저장할 dp 배열을 생성한다.(길이는 동일)
이중 반복문을 통해서 해당 원소 값이 그 이전 원소보다 크다면 메모이제이션된 dp에서 길이를 가져오는 식으로 로직을 구성하면 된다.
메모이제이션을 통해 그 이전 길이를 가져와야한다.
시간복잡도 - O(N^2): 이중 반복문 이용
공간복잡도 - O(N): 처음 배열 초기값
> 한현수 73일차 문제 풀이

- Study09 - Greedy/Day79/ysm.cpp
실패 원인
1. 길이에 대한 고려를 하지 않음 
단순히 알파벳 개수가 홀수인것이 여러개면 안된다라는 것만 규칙으로 생각함. 길이가 짝수일때 홀수가 존재하면 안된다는 규칙을 찾지 못함. 
2. reverse메소드 - 생각하지 못함 -> string + 중간알파벳 + string을 뒤집은것 에 대한 고려하지 않고 for문으로 다 하려했음
1. 문자열 길이가 짝수이면서 홀수가 존재하면 실패로 간주
2. 문자열 길이가 홀수이면서 홀수가 여러개여도 실패로 간주. 홀수가 1개만 있을경우 중간 문자로 기록하고 알바벳 개수 배열 숫자를 하나 줄임.
4. 위 2개의 규칙을 다 통과시 개수의 반을 string 문자열로 기록
5. middle 문자가 존재할 경우, 기록한 문자열 + 중간 문자 + 뒤집은 기록 문자열로 출력
시간복잡도 O(N^2) -> for문
공간복잡도  O(1)
> 79일차 유수민 문제풀이 실패

- Study09 - Greedy/Day78/hhs.java
- Study09 - Greedy/README.md
무게가 5, 3으로 나눌 수 있는 경우의 해를 구하는 문제.
총 4가지의 분기로 나뉜다.
1. 5의 무게로 전부 나뉘는 경우
2. 3, 5의 무게를 혼합해서 나뉘는 경우
3. 3의 무게로 전부 나뉘는 경우
4. 못 나누는 경우
순서대로 우선순위가 주어진다.
5로 전부 나눠지는 경우가 가장 최솟값이므로 먼저 비교한다.
만약 그러지 못한다면 5의 무게를 1개씩 증가시키면서 나머지 값들이 3으로 딱 나누어 떨어지는지 비교하여 값을 저장한다.
1, 2, 3 과정에서 최적 해를 찾지 못한다면 -1을 출력한다.
위와 동일
시간복잡도 - O(N): O(N/5) or O(N/3) ...
공간복잡도 - O(1)
> 한현수 78일차 문제 풀이

- Study09 - Greedy/Day79/hhs.java
- Study09 - Greedy/README.md
배열 - 알파벳들의 개수
먼저 입력받은 알파벳들의 개수를 센다.
그런다음 A-Z까지 순회하여 개수의 반 만큼 따로 StringBuilder에 각각 더한다.
이 과정에서 개수가 홀수라면 문자를 따로 저장한다.
StringBuilder에 저장된 값 + 홀수 문자 + StringBuilder에 저장된 값의 반대에서 입력받은 문자와 개수가 같다면 팰린드롬이고 다르면 팰린드롬이 아니다.
대칭이 되려면 각 문자들은 짝수여야한다. 만약 문자가 홀수라면 해당 문자가 가운데에 들어간다는 의미이다.
하지만 이 과정에서 각 문자가 홀수가 여러개라면 대칭이 될 수 없다. 따라서 팰린드롬이 아니다.
시간복잡도 - O(N): input의 문자 개수
공간복잡도 - O(N): 위와 동일
> 한현수 79일차 문제 풀이

- Study09 - Greedy/Day79/jhd.cpp
vector 배열입니다.
1. 뒤에서부터
2. 최대값과 다음 값을 비교한다.
3. 다음값이 더 크면 최대값을 바꾼다.
4. 최댜값이 변경되면 이윤은 0이됩니다.
5. 최대값보다 다음값이 작으면 최대값에서 다음값을 빼서 이윤에 더합니다.
이윤은 작을때 사서 비쌀때 팔아야합니다. 이 개념을 로직으로 구현했습니다.
시간복잡도 O(N)
공간복잡도 O(Z)
Z는 M의 최대값입니다.
> 정희두 80일차 문제풀이

- Study09 - Greedy/Day81/ysm.cpp
정렬까지는 해주는 것은 알았는데 그 뒤에 어떻게 해야할지 로직을 못짬. 알고리즘 이라는 틀에 박히지 말고 먼저 그림 그리기!!!!
1. ny < y 인 경우, 카메라의 위치를 ny로 옮기기 ! (1번 Case)
2. nx > y 인 경우, 카메라를 반드시 하나 더 설치해주기 ! (3번 Case)
3. nx < y < ny 인 경우, 카메라를 그대로 두면 된다. 따로 해줄 것이 없다 !
시간복잡도 O(N log N) -> 정렬
공간복잡도 O(N) -> routes 배열
> 유수민 81일차 문제풀이 실패

- Study09 - Greedy/Day81/kjh.py
- Study09 - Greedy/README.md
2차원 배열, 입력이 그렇게 주어짐
진출을 빨리 하는 순으로 정렬하고,
```
1. 빨리 진출하는 자동차의 진출 시점에 카메라를 설치하고
2. 해당 감시카메라에 걸리는 자동차들을 제외한다
```
위를 반복하면
최적의 카메라 수를 알 수 있다.
왜인지를 생각해봤을때 아래 논리를 따라간 것 같다는 결론에 이르렀다.
1. 감시카메라의 위치로 항상 '진출 시점'만을 사용해서 최적의 배치들을 해낼 수 있다.
* 우선 카메라는 '진입 시점' 또는 '진출 시점'으로만 두어도 된다는 점은 시간들여 생각해보면 알 수 있다.
* 진입 시점 초과 ~ 진출 시점 미만에 두어야만 풀릴 경우가 아무리 생각해봐도 없기 때문이다.
* '진출 시점'으로만 두어도 된다. 진입 시점으로 두어야만 풀릴 경우는 없기 때문이다.
2. 그러므로 가장 빨리 진출되는 자동차의 진출 시점에 카메라를 두는 것을 반복하면 최적의 배치를 해낼 수 있다.
시간복잡도 O(NlogN) : 정렬
공간복잡도 O(N)
풀이 실패
> 김진홍 81일차 문제풀이 실패

- Study09 - Greedy/Day81/kjh.java
- Study09 - Greedy/README.md
int 2차원 배열: 문제에서 주어짐
어레이리스트: 카메라를 담기 위해
진출을 빨리 하는 순으로 정렬하고,
```
1. 빨리 진출하는 자동차의 진출 시점에 카메라를 설치하고
2. 해당 감시카메라에 걸리는 자동차들을 제외한다
```
위를 반복하면
최적의 카메라 수를 알 수 있다.
시간복잡도 O(NlogN)
공간복잡도 O(N)
> 김진홍 81일차 문제 재풀이

- Study09 - Greedy/Day81/hhs.java
- Study09 - Greedy/README.md
배열 - 값들을 저장한다.
문제의 요점은 각 구간에서 최소의 카메라를 설치하는 것이다.
위를 판단하기 위해서는 끝점을 기준으로 정렬을 해야한다.
정렬한 구간을 순서대로 표현하면 아래와 같다. (예시: [[-20,-15], [-14,-5], [-18,-13], [-5,-3]])
따라서 해당 선분의 끝점이 다음 선분의 시작점보다 크거나 같은지 비교한다 -> 조건에 맞는다면 해당 위치는 겹쳐서 카메라를 동시에 놓을 수 있다. 틀리다면 겹치지않는것이다 따라서 카메라를 더 추가해야함
그러면 겹치지 않는다면 끝점을 다시 최신화하여 다음선분과 똑같이 비교하면된다.
최적의 해를 구하기 위해서는 정렬이 필요함 -> 유망하는 선분은 해당 선분과 겹쳐야한다. 값이 뒤죽박죽이면 유망하는 선분을 찾을 수 없다. 
시간복잡도 - O(N log N): 정렬
공간복잡도 - O(N): routes의 개수
각 route를 수학적으로 선분이라 판단하니까 짐작이 가더라구요.
문제에는 안나와있지만 각 끝점은 해당 출발점보다 크거나 같다는 조건이 숨겨져 있는 것 같습니다. 틀리면 방향도 랜덤이라 생각해서 예외처리를 하려고했는데 따로 안해도 맞네요
> 한현수 81일차 문제 풀이

- Study09 - Greedy/Day82/kjh.kt
- Study09 - Greedy/README.md
T(문제에서의 목표 문자열)와 S(문제에서의 시작 문자열)의 길이가 같아질때까지 아래를 반복한다
* T의 마지막 문자가 A라면 A를 제거한다
* T의 마지막 문자가 B라면 B를 제거하고 뒤집는다
같아졌을때 T와 S가 같다면 1을 출력하고
다르다면 0을 출력한다
순방향으로 연산을 했을때 1번 연산을 했을까 2번 연산을 했을까는
마지막 문자가 무엇인지로 알 수 있다.
그러므로 마지막 문자를 기준으로 역방향 역산할 수 있다.
시간복잡도 O(N^2) : O(N)의 순회를 하는데 모든 문자가 B라면 또 그 안에서 O(N)의 reversed를 할 것이기 때문에
공간복잡도 O(N) : 문자열을 char배열로 봄
> 김진홍 82일차 문제 재풀이

- Study09 - Greedy/Day82/kjh.cpp
- Study09 - Greedy/README.md
T로부터 시작해서
마지막 글자를 기준으로 역순으로 연산을 진행해
S에 도달할 수 있다면 1을 출력하고
그렇지 않다면 0을 출력한다
S에서 T로 가는걸 고려하려면
1번 연산을 할지 2번 연산을 할지에 대한 경우의 수를 고려해야 하는데
T에서 S로 역방향으로 생각하면
마지막 글자를 기준으로 이미 해야하는 연산이 정해져있기때문에
경우의 수에 대한 고려 없이 O(N)으로 알 수가 있다...
시간복잡도 O(N^2) : O(N)의 순회를 하는데 순회 중 사용하는 reversed 함수가 O(N)이므로 최대 O(N^2)
공간복잡도 O(N) : 문자열을 char배열로 봄
문제 풀이 실패
> 김진홍 82일차 문제풀이 실패

- Study09 - Greedy/Day81/ysm2
- Study09 - Greedy/README.md
기본적인 for문 대신 forEach를 사용해봄 -> c++은 auto를 사용해야 한다!
1.  시작지점  <= 카메라 위치 < 빠져나간 지점 : 카메라 위치 그대로 -> 코드화 할 필요없음
2.  빠져나간 지점 < 카메라 위치 : 카메라위치를 빠져나간지점으로
3. 카메라위치 < 시작지점 : 카메라 위치를 바꾸고, 카메라 새로 설치하는 것으로
문제를 읽다보니 경우의 수가 3가지여서 그 경우로 나눠보았다.  
시간복잡도 O(NlogN) -> 정렬
공간복잡도 O(N) -> routes개수
> 유수민 81일차 문제재풀이

- Study09 - Greedy/Day82/ysm.cpp
그리디유형은 1) 경계의 문제로 선으로 그림그려가며 풀기 2) 거꾸로 생각하기 로 2가지 유형이 있는듯하다. 
* 의문점
input
ABB
BBAB
답 1
에서 왜 있는 그대로 A 더하고(ABBA) reverse하고(ABBA) B 붙이면 하면(ABBAB) BBAB가 절대 안나온다. reverse가 문자자체를 거꾸로 하는 것 아닌가? 이해가 안감. 어떻게 해서 나올 수 있는가? 
1. 결과문자의 마지막문자가 B일 경우 문자 끝에서 빼고 reverse한다. 
2. 결과문자의 마지막문자가 A일 경우 단순히 문자에서 끝을 뺀다
3. 처음 시작한 문자 길이가 나올때까지 반복한다. 
시간복잡도 O(NM) N: 제시한 결과 문자의 길이 M: reverse의 시간 
공간복잡도 O(N) N: 제시한 결과 문자
문자열 S를 변형시킬 수 있는 방법은 2가지 
(1) 문자열 뒤에 A를 추가
(2) 문자열 뒤에 B를 추가하고 뒤집기
T의 한계가 1000이니까 정석대로 한다면 2^1000으로 시간초과가 났을 것이다.
> 유수민 82일차 문제 풀이 실패

- Study09 - Greedy/Day82/ysm2.cpp
- Study09 - Greedy/README.md
string 이용 - pop_back()과 push_back()을 이용하기 위해
결과에서 만약 맨뒤 문자가 A면 단순히 문자를 빼고, B면 문자를 뺀다음 뒤집는다. 
시작길이가 될때까지 수행한다. 
문제 해석을 잘못했었던 것을 깨달음. 
* 문자열의 뒤에 A를 추가한다.
* 문자열을 뒤집고 뒤에 B를 추가한다.
이 둘 중 하나를 수행하는 거지 A를 추가하고 난후 문자열뒤집고 B 추가하는 것이 아니였음
둘중하나를 수행하는 것이기 때문에 그리디 알고리즘에 해당하는 거였음. 따라서 시작부터가 차례대로가 아닌 결과에서 시작을 찾는 방향이 올바른 거였음
시간복잡도 O(N^2) N: 제시한 결과 문자의 길이 N: while안의 reverse의 시간복잡도 따라서 N^2!
공간복잡도 O(N) ->  결과 string
> 유수민 82일차 문제 재풀이

- Study09 - Greedy/Day82/hhs.java
- Study09 - Greedy/README.md
최적의 해를 구하기 위해서는 문제에 나왔던 아래 조건을 잘 살펴봐야한다.
* 문자열의 뒤에 A를 추가한다.
* 문자열을 뒤집고 뒤에 B를 추가한다.
저것은 S -> T로 갈때의 조건이고 T -> S로 갈때의 조건을 생각해보자
1. 맨 뒤 문자가 'A'라면? -> 문자열의 뒤에 A를 추가한다. 를 수행한 후다. T에 'A'를 삭제하자.
2. 맨 뒤 문자가 'B'라면? -> 문자열을 뒤집고 뒤에 B를 추가한다. 를 수행한 후다. T에 'B'를 삭제한 후 문자열을 다시 뒤집는다.
위 1, 2 과정을 T와 S의 길이가 동일할 때까지 반복한다.
마지막에 T와 S를 비교하여 맞다면 1 틀리다면 0을 출력한다.
마지막 문자가 'A'라면 (문자열을 뒤집고 뒤에 B를 추가한다.) 를 수행한 후가 절대 될 수 없다. -> 만약 이게 된다면 모든 답은 0이 될 거나 판단 할 수 없다.
'B'인 경우도 마찬가지 이다.
즉 이미 답은 정해져 있기 때문에(S가 주어졌다는 것은 답은 이미 정해져 있다는 의미) T의 마지막 문자를 계속 비교하면서 S까지 가면 된다.
시간복잡도 - O(T.length() - A.length()): T의 길이가 A의 길이가 될 때까지 반복해야한다. 
공간복잡도 - O(T): 초기값
처음에는 BFS 문제(브루트포스)가 아닐까 싶다가 당연히 메모리 초과 or 시간 초과가 일어날 줄 알면서도 풀어봤습니다 ㅋㅋㅋ
> 한현수 82일차 문제 풀이

- Study09 - Greedy/Day84/hhs.java
- Study09 - Greedy/README.md
배열 - Union, Find 연산을 하기위해
최소 신장 트리를 찾는 알고리즘을 사용하면된다.
1. 프림
2. 다익스트라
3. 크루스칼
본 문제를 크루스칼 알고리즘을 이용하여 풀었다.
크루스칼 알고리즘은 간선의 가중치를 기준으로 오름차순 정렬을 한뒤 최소간선을 선택하여 순차적으로 연결해봐서 사이클이 안도는지 확인한다.
그리고 모든 정점을 연결해서 가중치들을 더하면 된다.
여기서 사이클이 안도는지 확인하려면 union, find 연산을 진행해야한다.
union은 노드의 집합, find는 노드의 부모를 찾는 연산이다.
*최소의 비용으로 모든 섬이 서로 통행 가능하도록 만들 때 필요한 최소 비용*
문제 조건을 보고 바로 최소 신장 트리 문제라고 생각했다.
또한 N의 범위가 1~100이므로 간선이 적어서 크루스칼 알고리즘을 사용했다.
그리고 크루스칼은 비교적 구현하기가 쉽다. ~~이해하기가 어려울 뿐~~
시간복잡도 - O(E log E) : E = 간선의 개수 = costs의 길이, costs를 정렬했기 때문
공간복잡도 - O(E): 위와 동일
union, find 연산은 O(1)이다. 따라서 정렬의 시간복잡도가 더 크다.
> 한현수 84일차 문제 풀이

- Study10 - Graph And DFS/Day86/hhs.java
- Study10 - Graph And DFS/README.md
List - V, E를 가변적으로 저장하기 위한 용도.
V, E를 입력받고 해당 간선의 정보를 List에 저장한다.
그리고 dfs를 1부터 수행하면서 counting을 시도하면 된다.
주의해야할 점은 1번 컴퓨터는 이미 감염된 상태이기때문에 1번은 counting에서 제외
1번과 연결된 정점들을 모두 봐야하기 때문에 DFS or BFS 알고리즘이 필요하다.
시간복잡도 - O(V + E): 모든 정점과 간선들을 본다.
공간복잡도 - O(V + E): 위와같이 그만큼 재귀적으로 함수를 호출한다.
> 한현수 86일차 문제 풀이

- Study10 - Graph And DFS/Day88/ysm.cpp
- Study10 - Graph And DFS/README.md
놀랍게도 이거 프로그래머스 레벨 3임... dfs 문제인거 알고 하니까 쉬움 이문제가 dfs인지 아닌지 판단하는 거가 어려워서 레벨 3인듯
방문했던 노드인지 판단하고 방문을 안했다면, 해당 노드와 연결된 것들을 다 파악하기 위해 dfs를 사용한다. 
연결유무가 인접행렬로 제시되어 있고 한줄로 연결된 것들을 파악해서 한 묶음으로 만들고 묶음 개수를 파악하는 것이기 때문에 dfs를 사용해야 할듯 싶다. 
시간복잡도 O(N) 제시한 노드를 방문할 최대개수는 N번이기 때문
공간복잡도 O(N^2) - computers
한시간째 이러고 앉아있음--;;  따로 돌려본결과 테스트 케이스는 일단 통과니까 후에 다시 채점하겠음
> 유수민 88일차 문제풀이

- Study11 - Graph And BFS/Day92/kjh.kt
- Study11 - Graph And BFS/README.md
(1, 1) 정점에서 시작해
아래를 반복한다
* 상하좌우에 있는, 아직 방문하지 않은, 이동할 수 있는 칸을 queue에 추가한다
* (N, M)에 도달하면 도달 당시의 depth를 출력하고 프로그램을 종료한다
최단거리는 뭐다? BFS다.
시간복잡도 O(NM) == O(NM+4NM) : 최악의 경우 모든 정점(NM)을 방문하며 모든 간선(4*NM)을 지남
공간복잡도 O(NM) : 모든 정점이 들어가는게 최악의 경우
> 김진홍 92일차 문제 풀이

- Study11 - Graph And BFS/Day93/ysmC.cpp
- Study11 - Graph And BFS/Day93/ysmMine.cpp
난 단순히 for문만을 이용했고, 사실  bfs를 써야한다는 건 알았는데 어떻게 연결짓지? 에서 막혔다. 결국 제한시간내에 dfs/bfs와 연결짓지 못했으니 실패로 하겠다. 내 코드도 같이 올림. 
1. 그래프를 입력받고 국경을 열 수 없을 때까지 while문을 돌립니다.
2. while문을 한번 돌릴 때마다 visited 배열을 초기화시키고 결과를 1 증가시킵니다.
3. 모든 칸을 순회하며 방문하지 않은 칸을 기준으로 벡터 v에 좌표를 추가하고 DFS 함수를 호출합니다.
4. DFS 함수는 다음 칸이 범위 내에 있고 아직 방문하지 않았으며 현재칸과 다음칸의 차이가 L 이상 R 이하일 경우에만 재귀 호출을 하며 국경을 엽니다.
5. 4번에서 국경을 열 때 벡터 v에 다음칸 좌표를 넣어주고 국가의 수도 늘어났기 때문에 num도 1 증가시켜줍니다.
6. 4번의 과정이 다 끝난 뒤에는 모든 칸마다 순회하며 인구를 (연합군의 수)/(국가의 수)로 바꿔줍니다.
시간복잡도 O(N^2) 최악의 경우 모든 곳을 다 탐색, 아마 visited때문에 불필요한 탐색은 하지 않아서 이것보다는 작을 것 같다. -> 잘 모르겠음...
공간복잡도 O(1)
> 93일차 유수민 문제실패

- Study11 - Graph And BFS/Day95/ysmC.cpp
- Study11 - Graph And BFS/Day95/ysmFail.cpp
테스트케이스 25가 계속 틀리는데 어떻게 고쳐야 하는 것인지 아직도 이해못함...ㅠㅜ 내 풀이(ysmFail)도 넣음
1. 방향이 같으면 100, 다르면 꺾고 직진이므로 600 을 추가한다
2. 방문하지 않았거나 길이가 지금 확장하려는 길이보다 길거나 같으면 확장한다.
3. 목표 지점에 도착했으면 비용을 계산하고 최소 값을 구한다.
시간복잡도 O(N^2) 인접행렬형태라 최악의 경우 모든 지점 다 탐색
공간복잡도 O(N^2) 인접행렬
> 유수민 95일차 문제 풀이 실패

- Study11 - Graph And BFS/Day95/sjw.java
- Study11 - Graph And BFS/README.md
요구사항. NxN 배열내 [0][0] -> [N-1] [N-1] 에 도달하는 과정에서 비용이 제일 적은 것을 출력하라
1. 각 좌표 값마다 4개의 방향에서 들어올수 있음 -> int[][][4]로 방문 체크를 하면서 비용을 저장함
2. 벽으로 막혀있는 좌표값은 피하고, NxN 범위 내에서 탐색할 수 있게 설정
3. 탐색하면서 visited의 저장된 비용보다 현재 비용이 더 적을 경우만 비용 계산
4. 모든 방향을 돌면서 최솟값을 갱신 후 반환.
단순하게 최단 거리 문제니까 BFS를 활용하여 풀자. 라고 생각함
-> 틀림
이유는 아래 케이스가 존재하기 때문
좌표에 최소 비용을 저장하는 로직에 들어오는 경로간 좌표가 겹치는 경우 발생
-> 당장 어느 한 a 좌표의 최소비용을 저장하더라도 나중에 결과값이 역전되는 현상이 발생함.
{0, 0, 0, 0, 0},
{0, 1, 1, 1, 0},
{0, 0, 1, 0, 0},
{1, 0, 0, 0, 1},
{0, 1, 1, 0, 0}
.. 1) 밑 방향으로 간 경우  2) 우 방향으로 간 경우 각각 [3][3] 에서 1) 2100, 2) 2300 이지만 결과를 놓고 보면 1) 3300, 2) 3000 으로 2번이 더 최소비용이다.
위의 케이스의 경우을 고려하여 들어오는 방향 또한 저장하여 최소 비용을 비교할 때 사용하는 게 **keyPoint** 임 
시간복잡도 O(n^2) - 보드배열 전부 탐색하기 때문
공간복잡도 O(n^2) - 보드 배열의 크기가 N*N
> * 직관적이고 아주 잘 …
> 신지우 95일차 문제풀이

- Study11 - Graph And BFS/Day94/sjw.java
0이상 100,000 이하의 범위에서 N이 K까지 도달하는 데 걸리는 최소 시간을 구하면 된다. 
여기서 1초마다 위치 N은 X-1, X+1로 이동할 수 있고, 순간이동을 하면 0초 후 2X의 위치로 이동한다
1. 큐에 있는 point 객체를 꺼내서 방문처리 한다음 현재 pos가 K와 같은지 확인하고 같다면 , 현재 time을 반환.
2. 0이상 100,000 이하의 범위내에서 방문하지 않은 case에 맞쳐서 각 노드를 큐에 하나씩 넣기. (최소 비용인 순간이동부터 시작)
최소 비용을 구하는 문제였기 때문에 반사적으로 bfs를 떠올림
1. 최소 비용인 순간이동 부터 계산해줬어야 했는데 그걸 놓쳤었고
2. 범위 오타도 있었음 (이전 풀이에 1000000 으로 범위지정,,,,)
시간복잡도 O(N*100000) -정점에 3개씩 불어나서 문제의 범위 최대 100000 만큼 생길 수 있음
이전 생각했던 시간복잡도 O(NlogN) (이)가 아니라고 생각하는 이유 - 우선 logN의 시간복잡도가 되려면 이진트리를 생각하면 된다.
이진트리의 경우 매 탐색마다 탐색해야할 노드의 수가 절반씩 준다. 그래서 logN임.
하지만 해당문제의 경우 탐색횟수가 절반씩 줄어드는 형태는 아니므로 적합해보이지 않음.
공간복잡도 O(100001) - 100001 배열 사용
> * 대체적으로 잘 이해되는 편이나, 추상적이어서 설명을 …
> 신지우 94일차 문제 재풀이

- Study11 - Graph And BFS/Day92/ysmReC.cpp
- Study11 - Graph And BFS/README.md
시작하는 점에서 상하좌우를 탐색하여 갈 수 있는 곳이면(이전에 방문하지 않았고, 1이라 표시된곳) 큐에 기록해놓고, 시작점으로부터 해당값까지의 거리를 시작점의 dist값 +1을 하여 맨 처음 시작점(0,0)으로 부터의 거리를 기록한다.
도착지점까지 최소의 칸 수를 구해야 하므로 bfs를 이용해야 한다는 것은 이전부터 알고 있었으나 지금까지는 응용을 잘 못했는데 이제는 아래 내용을 더 알게되어서 
처음 풀이와 달라진 점
* 좌표에 대해 어떻게 하나 고민이 많았는데 구조체를 이용하면된다는 것을 이제 알고 있음
* 처음좌표와의 거리에 대한 배열이 필요하다는 것을 이제 알고 있음
풀이가 가능해졌다. 
시간복잡도 O(NM) -> 최악의 경우 모든 배열을 다 탐색해야함.
공간복잡도 O(1) 
야홋😆
> 유수민 92일차 문제재풀이

- Study11 - Graph And BFS/Day94/ysmReC.cpp
- Study11 - Graph And BFS/README.md
1. 경과시간을 기준으로 경과시간이 짧을 수록 먼저 탐색하도록 한다. {경과시간,계산값}으로 쌍으로 큐에 넣는다.
2. 방문체크를 하여 이미 방문한 것은 큐에 넣지 않도록 한다.
3. 순간이동한 경우 시간이 달라지지 않으므로 경과시간을 다르게 하지 않으면서 큐에 넣는다.
4. +1,-1의 경우, 경과시간+1을 하고 큐에 넣는다.
5. 답이 나올때까지 반복한다.
이번문제는 사실상 dfs가 아닌 약간 구현문제에 가까운것 같다. 이전에 풀어봤어서 시간을 누적할만한 요소가 필요하다는 것을 알았다. 다만 그전과 문제들과 달리 따로 배열로 풀기보다는 key,value를 이용한다는 점이 달랐다. 계산한 수의 범위가 100001을 넘지 않아야 한다는 조건이 없으니 outofBound가 나온다는 것도 이번에 확인했다.   
또한, 한가지 더 생각할 점은,2를 곱한 값은 time이 다른 계산값보다 작다는 특징을 가졌다. 즉, 가중치가 0이기 때문에 먼저 k와 비교해야한다는 것이다. 따라서 우선수위큐를 사용해야한다. 
시간복잡도 O(ElogE) E: 간선의 개수, 우선순위큐를 사용했기 때문에
공간복잡도 O(E) 우선순위큐에 쌓이는 간선의 개수
> 유수민 94일차 문제 재풀이

- Study11 - Graph And BFS/Day95/ysmReC.cpp
1. (0,0)으로 들어올 수 있는 방향이 위에서 아래, 왼쪽에서 오른쪽이므로 이 두 방향에 대해 큐에 넣어주고 시작한다. 
2. costMap배열은 상하좌우 방향에 대한 비용값이다. 최소의 비용값으로 비교하면서 저장되어야 하기 때문에 초기화를 큰값으로 하였다.
3. 현재방향과 일치하면 출발한 곳의 비용 + 100, 다르면 +600을 한다. 
코너는 일직선으로 간 후 틀어야 하기 때문에 500에 100을 더한 값으로 계산해야한다. 
4. 다른 지점으로부터 최종도착점까지 오는 것들을 모두 비교하여 최소 비용값을 출력값으로 지정한다. 
우선적으로 저번에 25번케이스가 왜 계속 틀렸는지 이제 알았다. 
난 단순히 costMap배열을 상하좌우 방향에 대한 고려없이 사용했는데 이것에 대한 고려가 필요했다. 시간이 진짜 오래걸렸다.ㅜㅡ 진짜 코딩테스트였으면 틀렸을 문제일듯ㅠㅜ 이제서라도 이해해서 다행..
시간복잡도 O(N^2) 인접행렬형태라 최악의 경우 모든 지점 다 탐색
공간복잡도 O(N^2) 인접행렬
> 유수민 95일차 문제 재풀이

- Study12 - Tree/Day104/kjh.kt
- Study12 - Tree/README.md
1. 입력을 참고해 트리를 만들고
2. 그 트리에 대해 전위/후위 순회한 결과를 출력한다
입력으로 트리를 만드는 방법
* 루트 노드부터 시작해서 리프노드까지 내려가며 아래를 반복한다
1. 자식들이 몰려있는 y좌표를 찾는다 (현 노드의 y보다 큰 것 중 가장 작은 것)
2. 해당 y좌표의 모든 노드들을 담아둔다
3. 내가 부모의 왼쪽 자식이라면 담아 둔 노드 중 부모의 x보다 작은 것들만 남긴다
4. 내가 부모의 오른쪽 자식이라면 담아 둔 노드 중 부모의 x보다 큰 것들만 남긴다
5. 담은 노드 중 나의 x보다 작은 것은 left, 나의 x보다 큰 것은 right다
3, 4번은 코드에서는 moreThan, lessThen 변수를 사용해 구현하였음
로직 고민했던 흔적
어떻게 '나의 left'와 '나의 right'가 무엇인지를 구별해내는가가 고민이였다
부모, 조부모, 증조부모의 왼쪽 자식이냐 오른쪽 자식이냐가
구별해내기 위해 꼭 필요한 정보더라
이것을 코드 상으로 어떻게 표현하느냐도 고민이였는데
최종적으로 moreThan(이것보다 커야한다는 기준), lessThan(이 변수보다 작아야한다는 기준)으로 표현하게 됐다
내가 부모의 왼쪽자식이라면
부모의 x보다 작아야 한다
그러면 lessThan = 부모.x-1로 하면 된다
그대로 구현했더니 맞았다
_N=노드의 개수_
시간복잡도 O(N^2) : N개의 노드에 대해 O(N) 연산을 하는 filter, find, firstOrNull 등의 연산을 하므로
공간복잡도 O(N)
```⭐️x10 완벽해요!```
> 2. …
> 김진홍 104일차 문제 풀이

- Study13 - Prefix Sum/Day106/ysmC.cpp
아침까지 내 풀이가 왜 틀렸는지 찾다가 못찾아서 해답을 보았다. 윈도우 슬라이스를 이용한 것은 맞는데 누적합을 이용했다고는 할 수 없었다.  
1. 1부터 k까지 깨진 것을 센다(cnt).  
2. 이제 K+1부터 시작해서 이번 구간의 끝이 깨진게 있으면 cnt를 더하고 이전 구간의 첫번째 인덱스가 깨진것이면 cnt를 뺀다. 
3. min값과 비교해서 최소 cnt를 min값으로 저장한다
시간복잡도 O(N) - for문
공간복잡도 O(1)
```⭐️x10 완벽해요!```
> 106일차 유수민 문제풀이 실패

- Study13 - Prefix Sum/Day106/ysmC.cpp
- Study13 - Prefix Sum/README.md
1.1부터 k까지 깨진 것을 센다(cnt).
2.이제 K+1부터 시작해서 이번 구간의 끝이 깨진게 있으면 cnt를 더하고 이전 구간의 첫번째 인덱스가 깨진것이면 cnt를 뺀다.
3.min값과 비교해서 최소 cnt를 min값으로 저장한다
이전 풀이에서 윈도우풀이라는 것이 끝에 값에 따라 기존에 계산된 값에서 더하거나 빼주고, 범위에 벗어나는 곳의 값도 기존에 계산된 값에 반영해야한다는 것을 알고 문제풀이를 하니 쉽게 풀렸다. 
시간복잡도 O(N) - for문
공간복잡도 O(1)
```⭐️x10 완벽해요!```
> 106일차 유수민 문제 재풀이

- Study13 - Prefix Sum/Day107/ysmC.cpp
해당 구간의 합을 구하기 위해 누적합이 계산된 배열을 이용하는 문제.
이전에 풀었을때 몰랐던 점을 기억하면서 풀이
시간복잡도 O(N^2) 누적합 계산
공간복잡도 O(1) 
```⭐️x10 완벽해요!```
> 107일차 다시 풀어봤으면 하는 문제 재풀이

- Study13 - Prefix Sum/Day109/ysmC2.cpp
1. 주어지는 지점 개수의 2배만큼의 사이즈를 가진 누적 배열(arr)을 만든다.
2.  누적합을 계산한다.
3. 시계방향은 arr[가는 지점] - arr[시작지점],  반시계방향 arr[시작지점 + N] - arr[가는지점]중 더 작은 값이 값이 된다. 
4. 전체 값중 최소 값을 찾는다. 
이전에 봤던 답이 생각이 안나서 어떻게 풀까 하다가 원형이라고 한다면 이것을 일렬로 만드면 되지 않을까해서 생각함
시간복잡도 O(N^2) - 최소 거리 찾기 계산
공간복잡도 O (N) -  누적합
```⭐️x10 완벽해요!```
> 109일차 문제 재풀이

- Study13 - Prefix Sum/Day110/ysm2C.cpp
- Study13 - Prefix Sum/README.md
확실히 실패한거 한번 더 푸니까 좋음. 
1. 위 그림처럼 각각의 변화도를 기록한다.
2. 왼쪽에서 오른쪽 누적합을 구한다.
3. 위에서 아래 누적합을 구한다.
4. 누적합과 board 를 합친다.
다시 풀때 걸렸던 점
2번의 경우 왼쪽에서 오른쪽 누적합을 구할때 x 범위를 더 늘려야 생각했는데 y범위를 더 늘렸어야 했다. 3번도 마찬가지. y범위가 아닌 x 범위를 더 늘렸어야 했다. 
이전 풀이에서 알게되었던 아이디어를 생각하며 풀었다. 
시간복잡도 O(NM) 누적합 계산
공간복잡도 O(1)
```⭐️x10 완벽해요!```
> 유수민 110일차 문제 재풀이
